language: python
python:
    - "2.7"
    - "3.0"
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
install:
    - "pip install ."
    - "pip install flake8 flake8-docstrings"
    - "pip install -r requirements.txt"
script:
    - "python tests.py"
    - "python -m flake8 pythonwars/"
