language: python
python:
    - "3.5"
install:
    - "pip install ."
    - "pip install flake8"
    - "pip install -r requirements.txt"
script:
    - "python3 tests.py"
    - "python3 -m flake8 pythonwars/"
